### ISSUE TITLE
Error when trying to get aanswer

### ISSUE THREAD

**Issue by Constey** [dirk-weimar/let-me-confluence-that-for-you#4]
Hi Dirk, 
that looks nice, i've tried it, and can create the embeddings (csv is created) but when asking a question I'm receiving an exception where i'm not sure where I have to look. Could you give me a hint, whats wrong here?

`UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('int64'), dtype('<U3')) -> None
Traceback:
File "C:\temp\confgpt\venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "C:\temp\confgpt\let-me-confluence-that-for-you\app.py", line 237, in <module>
    response = ask(prompt, st.session_state.messages, pages_df)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\temp\confgpt\let-me-confluence-that-for-you\app.py", line 104, in ask
    context = get_context(query, pages_df_sorted)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\temp\confgpt\let-me-confluence-that-for-you\app.py", line 145, in get_context
    chosen_pages_links.append(page.space + ': [' + page.title +']' + '(' + page.link + ')')
                              ~~~~~~~~~~~^~~~~~~`

one thing i noticed: when using a local confluence datacenter version and the api key authentication, the connection string must be this way:
    #confluence = Confluence(url = url, username = username, password = api_token, cloud = True)
    confluence = Confluence( url=url,  token=api_token)
    
(the cloud parameter does not work for me)

Kind regards,
Constantin

**Comment by dirk-weimar** [comment]
Hey Constantin, I understand you are using the local datacenter version of Confluence. I can only guess that the API differs from the API of the cloud version of Confluence. I only tested the cloud version. Sorry for not having a solution for that. Cheers, Dirk
